### ISSUE TITLE
lack of jammer causes issue in jammer stats

### ISSUE THREAD

**Issue by spikenheimer** [AdamSmasherDerby/crgscreenpack#1]
if a jam does not have a jammer of record listed, the two jammer stats views will stop at that jam.

tested this with some scoreboard data i'd downloaded from derbystats.eu.  as i went into the scoresheet and added jammers to those jams, more data would appear in the stats-views.

can also recreate by performing in the reverse - set a jammer to `none/unknown` and data parsing ceases

**Comment by AdamSmasherDerby** [comment]
Well crumbs.  Probably something that got lost in the transition to 4.0.  I'll work on that this weekend.

**Comment by AdamSmasherDerby** [comment]
Hopefully fixed by 90ae4c08693f20aa27b77dafba5620e3f960e4fd
